Repository madlabsinc/teachcode, pull requests merged in 2019-10, with the labels that each got.

#18 chore: refactor code
  src/utils/validate.js
Labels: Hacktoberfest, code refactoring

#20 refactor: improve lint
  .eslintrc.js
  bin/index.js
  package.json
  src/commands/init.js
  src/commands/submit.js
  src/utils/github.js
Labels: Hacktoberfest, code refactoring

#21 Update README.md
  README.md
  docs/guide/README.md
Labels: Hacktoberfest, docs

#25 Chore(Solutions): Use const and let not var
  src/workspace/js/solutions/task10.js
  src/workspace/js/solutions/task11.js
  src/workspace/js/solutions/task2.js
  src/workspace/js/solutions/task3.js
  src/workspace/js/solutions/task4.js
  src/workspace/js/solutions/task5.js
  src/workspace/js/solutions/task6.js
  src/workspace/js/solutions/task7.js
  src/workspace/js/solutions/task8.js
  src/workspace/js/solutions/task9.js
Labels: Hacktoberfest, code refactoring

#26 Feat(Task 12): adds task 12, its solution and some QOL
  src/workspace/js/solutions/task12.js
  src/workspace/js/tasks.json
Labels: Hacktoberfest, enhancement

#32 Fixed misleading usage info when calling teachcode
  bin/index.js
  test/snapshots/index.js.md
  test/snapshots/index.js.snap
Labels: Hacktoberfest, code refactoring

#19 Update README.md
  README.md
Labels: Hacktoberfest, docs

#34 Update README.md
  README.md
Labels: Hacktoberfest, docs

#31 Add didyoumean
  bin/index.js
  package-lock.json
  package.json
Labels: Hacktoberfest, enhancement

#33 Adopt commitlint standards
  README.md
  commitlint.config.js
  docs/guide/contributing.md
  package-lock.json
  package.json
  test/index.js
Labels: Hacktoberfest, enhancement

#40 feat: add -V and --version e2e test
  package-lock.json
  test/index.js
  test/snapshots/index.js.md
  test/snapshots/index.js.snap
Labels: Hacktoberfest, enhancement

#41 JS Tasks Addition
  package-lock.json
  src/workspace/js/solutions/task13.js
  src/workspace/js/solutions/task14.js
  src/workspace/js/solutions/task15.js
  src/workspace/js/solutions/task16.js
  src/workspace/js/solutions/task17.js
  src/workspace/js/solutions/task18.js
  src/workspace/js/solutions/task19.js
  src/workspace/js/solutions/task20.js
  src/workspace/js/solutions/task21.js
  src/workspace/js/solutions/task22.js
  src/workspace/js/solutions/task23.js
  src/workspace/js/solutions/task24.js
  src/workspace/js/solutions/task25.js
  src/workspace/js/solutions/task26.js
  src/workspace/js/solutions/task27.js
  src/workspace/js/solutions/task28.js
  src/workspace/js/solutions/task29.js
  src/workspace/js/solutions/task30.js
  src/workspace/js/tasks.json
Labels: enhancement
