Repository madlabsinc/teachcode, pull requests merged in 2020-11, with the labels that each got.

#96 refactor: leverage helpers
  __e2e__/__snapshots__/__e2e__/cli.test.js.md
  __e2e__/__snapshots__/__e2e__/cli.test.js.snap
  __e2e__/__snapshots__/__e2e__/commands/fetchtask.test.js.md
  __e2e__/__snapshots__/__e2e__/commands/fetchtask.test.js.snap
  __e2e__/__snapshots__/__e2e__/commands/showkeys.test.js.md
  __e2e__/__snapshots__/__e2e__/commands/showkeys.test.js.snap
  __e2e__/cli.test.js
  __e2e__/commands/fetchtask.test.js
  __e2e__/commands/helpers.js
  __e2e__/commands/showkeys.test.js
  bin/index.js
  package-lock.json
  package.json
  src/commands/init.js
  src/commands/keys.js
  src/commands/submit.js
  src/commands/tasks.js
  src/utils/logger.js
Labels: code refactoring

#95 chore: migrate to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: Hacktoberfest

#98 chore: bump commander
  bin/index.js
  package-lock.json
  package.json
Labels: dependencies

#99 chore: bump execa
  __e2e__/commands/fetchtask.test.js
  __e2e__/commands/init.test.js
  __e2e__/commands/showkeys.test.js
  __e2e__/commands/submit.test.js
  package-lock.json
  package.json
  src/utils/github.js
Labels: dependencies
