Repository madlabsinc/teachcode, pull requests merged in 2020-01, with the labels that each got.

#68 [Docs]: Added screenshots as part of the instructions
  docs/guide/README.md
Labels: docs

#64 chore: e2e test case for fetchtask
  __e2e__/__snapshots__/__e2e__/commands/fetchtask.test.js.md
  __e2e__/__snapshots__/__e2e__/commands/fetchtask.test.js.snap
  __e2e__/commands/fetchtask.test.js
  src/commands/tasks.js
Labels: enhancement

#74 Minor issue fix
  src/commands/init.js
  test/snapshots/index.js.md
  test/snapshots/index.js.snap
Labels: bugfix
